import { PERMISSIONS } from './permissions.js';

/**
 * 5 Hierarchical Access Roles Definition & Permission Mapping
 */
export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MANAGER: 'manager',
  AFFILIATE: 'affiliate',
  VIEWER: 'viewer'
};

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_MANAGE_ROLES,
    PERMISSIONS.USERS_MANAGE_OWNER,

    PERMISSIONS.OFFERS_READ,
    PERMISSIONS.OFFERS_CREATE,
    PERMISSIONS.OFFERS_UPDATE_OWN,
    PERMISSIONS.OFFERS_UPDATE_ALL,
    PERMISSIONS.OFFERS_DELETE_OWN,
    PERMISSIONS.OFFERS_DELETE_ALL,
    PERMISSIONS.OFFERS_FEATURE,
    PERMISSIONS.OFFERS_APPROVE,

    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.PRODUCTS_MANAGE,

    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.SETTINGS_CRITICAL,
    PERMISSIONS.LOGS_VIEW
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_MANAGE_ROLES,

    PERMISSIONS.OFFERS_READ,
    PERMISSIONS.OFFERS_CREATE,
    PERMISSIONS.OFFERS_UPDATE_OWN,
    PERMISSIONS.OFFERS_UPDATE_ALL,
    PERMISSIONS.OFFERS_DELETE_OWN,
    PERMISSIONS.OFFERS_DELETE_ALL,
    PERMISSIONS.OFFERS_FEATURE,
    PERMISSIONS.OFFERS_APPROVE,

    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.PRODUCTS_MANAGE,

    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.LOGS_VIEW
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.OFFERS_READ,
    PERMISSIONS.OFFERS_CREATE,
    PERMISSIONS.OFFERS_UPDATE_OWN,
    PERMISSIONS.OFFERS_UPDATE_ALL,
    PERMISSIONS.OFFERS_DELETE_OWN,
    PERMISSIONS.OFFERS_DELETE_ALL,
    PERMISSIONS.OFFERS_FEATURE,
    PERMISSIONS.OFFERS_APPROVE,

    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.PRODUCTS_MANAGE,

    PERMISSIONS.LOGS_VIEW
  ],

  [ROLES.AFFILIATE]: [
    PERMISSIONS.OFFERS_READ,
    PERMISSIONS.OFFERS_CREATE,
    PERMISSIONS.OFFERS_UPDATE_OWN,
    PERMISSIONS.OFFERS_DELETE_OWN
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.OFFERS_READ
  ]
};
